language: node_js
node_js:
- '4.2'
notifications:
  slack: adventure-cycling:tk7JVJnQzyDeWadDzfdxcZYT
before_script:
- npm run format
- npm run lint
after_success:
- npm run report
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
